language: ruby
cache: bundler

rvm:
  - 2.2.4

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - 'bundle exec rake db:create'
  - 'bundle exec rake db:migrate'

notifications:
  email:
    recipients:
      - simao.belchior@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: 49f907587e83d2737804911d7f022d51b9799654e79de36eb59a3799ad7d1423
